/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;

/**
 *
 * @author lguerrer17
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    Hora H, H2;

    public principal() {
        initComponents();

        cmdIgual.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdValidar.setEnabled(false);
        txtHora.requestFocusInWindow();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        cmdFijar = new javax.swing.JButton();
        cmdIgual = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdValidar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSegundos1 = new javax.swing.JTextField();
        txtHora1 = new javax.swing.JTextField();
        txtMinuto1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSegundos = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtMinuto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hora");
        setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 250, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdFijar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdFijar.setText("Fijar");
        cmdFijar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFijarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdFijar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        cmdIgual.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdIgual.setText("Igual");
        cmdIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIgualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, -1));

        cmdMostrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        cmdValidar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmdValidar.setText("Validar");
        cmdValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 110, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora n° 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Hora");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Minuto");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Segundos");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtSegundos1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSegundos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundos1KeyTyped(evt);
            }
        });
        jPanel4.add(txtSegundos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 50, -1));

        txtHora1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtHora1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHora1KeyTyped(evt);
            }
        });
        jPanel4.add(txtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, -1));

        txtMinuto1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMinuto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinuto1KeyTyped(evt);
            }
        });
        jPanel4.add(txtMinuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 50, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 170, 120));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora n° 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Hora");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Minuto");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Segundos");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtSegundos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSegundos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSegundosKeyTyped(evt);
            }
        });
        jPanel5.add(txtSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 50, -1));

        txtHora.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraKeyTyped(evt);
            }
        });
        jPanel5.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, -1));

        txtMinuto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMinuto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinutoKeyTyped(evt);
            }
        });
        jPanel5.add(txtMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 50, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(566, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIgualActionPerformed
        // TODO add your handling code here:

        Helper.mensaje(null, "" + H.compararhoras(H2) + "\n", "Mensaje", 1);

    }//GEN-LAST:event_cmdIgualActionPerformed

    private void cmdFijarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFijarActionPerformed
        // TODO add your handling code here:
        int h = 0, m = 0, s = 0, h2 = 0, m2 = 0, s2 = 0;
        int sw = 1;

        try {
            h = Integer.parseInt(txtHora.getText());
            m = Integer.parseInt(txtMinuto.getText());
            s = Integer.parseInt(txtSegundos.getText());
            h2 = Integer.parseInt(txtHora1.getText());
            m2 = Integer.parseInt(txtMinuto1.getText());
            s2 = Integer.parseInt(txtSegundos1.getText());
        } catch (NumberFormatException e) {
            Helper.mensaje(null, "Por favor digite horas validas", "Error", 2);
            sw = 0;
        }
        if (sw == 1) {
            H = new Hora(h, m, s);
            H2 = new Hora(h2, m2, s2);

            Helper.mensaje(null, "Horas establecidas correctamente", "Mensaje", 1);

            txtHora.setEditable(false);
            txtHora1.setEditable(false);
            txtMinuto.setEditable(false);
            txtMinuto1.setEditable(false);
            txtSegundos.setEditable(false);
            txtSegundos1.setEditable(false);
            cmdIgual.setEnabled(true);
            cmdMostrar.setEnabled(true);
            cmdValidar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdFijarActionPerformed

    private void cmdValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarActionPerformed
        // TODO add your handling code here:

        txtMostrar.append("La hora N°1 es: " + H.validarhora() + "\n"
                + "La hora N°2 es: " + H2.validarhora() + "\n");

    }//GEN-LAST:event_cmdValidarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        // TODO add your handling code here:

        txtMostrar.append("La hora N°1 es: " + H.mostrarhora() + "\n"
                + "La hora N°2 es: " + H2.mostrarhora() + "\n");

    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void txtHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtHoraKeyTyped

    private void txtMinutoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinutoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtMinutoKeyTyped

    private void txtSegundosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtSegundosKeyTyped

    private void txtHora1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHora1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtHora1KeyTyped

    private void txtMinuto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinuto1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtMinuto1KeyTyped

    private void txtSegundos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSegundos1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtSegundos1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdFijar;
    private javax.swing.JButton cmdIgual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdValidar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtHora1;
    private javax.swing.JTextField txtMinuto;
    private javax.swing.JTextField txtMinuto1;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtSegundos;
    private javax.swing.JTextField txtSegundos1;
    // End of variables declaration//GEN-END:variables
}
